[profile.default]
auto_detect_solc = true
via_ir = true
optimizer = true
optimizer_runs = 200
src = "src"
test = "test"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/"
]
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read-write", path = "./script/config/deployed" }
]

[rpc_endpoints]
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"
bsc_mainnet = "https://bsc-dataseed1.binance.org"
base_sepolia = "https://base-sepolia.infura.io/v3/fdcafc82230c43d79e3f265fa79b64c8"
eth_mainnet = "https://ethereum-rpc.publicnode.com"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
bsc_mainnet = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

[fmt]
line_length = 120
number_underscore = "thousands"
bracket_spacing = true
int_types = "long"

[lint]
exclude_lints = ["unsafe-cheatcode", "pascal-case-struct"]
